export const ADMIN_ROUTE = '/admin'
export const USER_ROUTE = '/user'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const FORM_ROUTE = '/form'
export const HOME_ROUTE = '/'
export const USER_LIST_ROUTE='/userList'